<?php
include_once('CasinoTableDto.php');
include_once('CheatRequestDto.php');
include_once('CheaterCardDto.php');
require_once('GameInstanceSetupDto.php');
include_once('GameResultDto.php');
include_once('GameStatusDto.php');
include_once('HiddenCardListDto.php');
include_once('NextCardListDto.php');
include_once('PlayerActionDto.php');
include_once('NextPokerMoveDto.php');
include_once('PlayerActionResultDto.php');
include_once('PlayerDto.php');
include_once('PlayerStatusDto.php');
?>
