<?php
include_once('BetDto.php');
include_once('CardNameListDto.php');
include_once('CasinoTableDto.php');
include_once('CheatRequestDto.php');
include_once('CheaterCardDto.php');
include_once('GameStatusDto.php');
include_once('NextPokerMoveDto.php');
include_once('PlayerDto.php');
include_once('PlayerHandDto.php');
include_once('PlayerStatusDto.php');
?>
